name: "Mypycify & Build Python Wheel"
description: "Build & cache a wheel for a mypyc C-extension, upload artifact for use, and optionally commit/PR non-.gitignored build files."
icon: package
color: blue
inputs:
  hash-key:
    description: "File globs (YAML list of strings) to include in the hash key for caching. This input is required."
    required: true
  python-version:
    description: "Python version to use (passed to actions/setup-python)"
    required: true
  pip-cache-dependency-path:
    description: "Dependency files for actions/setup-python pip cache. This input is passed directly to the 'cache-dependency-path' parameter of actions/setup-python."
    required: false
    default: ""
  ccache:
    description: "Enable ccache for C/C++ compilation (Linux/macOS only). Default: false."
    required: false
    default: "false"
  push-source:
    description: "Enable auto-commit and push or PR of changes if build output changes."
    required: false
    default: "false"
  commit-message:
    description: "Commit message to use when committing changes."
    required: false
    default: "chore: compile C files for source control"
  normalize-source:
    description: "Enable normalization of C files for diffchecking."
    required: false
    default: "false"
  trigger-pr-number:
    description: "Optional: PR number of the triggering PR (e.g., 1234). If set, the PR body will include 'Triggered by #<number>'."
    required: false
    default: ""
  trigger-branch-name:
    description: "Optional: Name of the triggering branch (e.g., feature/my-feature). Used in PR body if trigger-pr-number is not set."
    required: false
    default: ""
  build-command:
    description: "Custom build command to run (default: 'python -m build --wheel'). If you use a custom command, you are responsible for ensuring all requirements are installed before mypycify or as part of the build command."
    required: false
    default: "python -m build --wheel"
  build-from:
    description: "Where to build the wheel from. Allowed values: 'source' (default), 'sdist'."
    required: false
    default: "source"
outputs:
  artifact-name:
    description: "The name of the uploaded wheel artifact."
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      run: |
        set -e
        # Validate required inputs
        if [[ -z "${{ inputs.python-version }}" ]]; then
          echo "ERROR: python-version is required."
          exit 1
        fi
        if [[ -z "${{ inputs.hash-key }}" ]]; then
          echo "ERROR: hash-key is required."
          exit 1
        fi
        # Validate build-from
        if [[ "${{ inputs.build-from }}" != "source" && "${{ inputs.build-from }}" != "sdist" ]]; then
          echo "ERROR: build-from must be 'source' or 'sdist'. Got '${{ inputs.build-from }}'."
          exit 1
        fi
        # Validate ccache
        if [[ "${{ inputs.ccache }}" != "true" && "${{ inputs.ccache }}" != "false" ]]; then
          echo "ERROR: ccache must be 'true' or 'false'. Got '${{ inputs.ccache }}'."
          exit 1
        fi
        # Validate push-source
        if [[ "${{ inputs.push-source }}" != "true" && "${{ inputs.push-source }}" != "false" ]]; then
          echo "ERROR: push-source must be 'true' or 'false'. Got '${{ inputs.push-source }}'."
          exit 1
        fi
        # Validate normalize-source
        if [[ "${{ inputs.normalize-source }}" != "true" && "${{ inputs.normalize-source }}" != "false" ]]; then
          echo "ERROR: normalize-source must be 'true' or 'false'. Got '${{ inputs.normalize-source }}'."
          exit 1
        fi
        # Validate build-command
        if [[ -n "${{ inputs.build-command }}" && -z "$(echo "${{ inputs.build-command }}" | xargs)" ]]; then
          echo "ERROR: build-command must be a non-empty string if provided."
          exit 1
        fi
        # Combination: normalize-source requires push-source
        if [[ "${{ inputs.normalize-source }}" == "true" && "${{ inputs.push-source }}" != "true" ]]; then
          echo "ERROR: normalize-source cannot be true unless push-source is also true."
          exit 1
        fi
        # Combination: push-source requires at least one trigger
        if [[ "${{ inputs.push-source }}" == "true" && -z "${{ inputs.trigger-pr-number }}" && -z "${{ inputs.trigger-branch-name }}" ]]; then
          echo "ERROR: push-source is true, but neither trigger-pr-number nor trigger-branch-name is set. At least one is required for PR/commit automation."
          exit 1
        fi
      shell: bash

    - name: Compute hash key
      id: hash_key
      run: echo "hash-key=${{ hashFiles(inputs.hash-key) }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Compute unique artifact key
      id: artifact_key
      shell: bash
      run: |
        ARCHITECTURE="$(uname -m)"
        ARTIFACT_KEY="${{ runner.os }}-${ARCHITECTURE}-py${{ inputs.python-version }}-${{ inputs.build-from }}-${{ steps.hash_key.outputs.hash-key }}"
        echo "artifact-key=$ARTIFACT_KEY" >> $GITHUB_OUTPUT

    - name: Cache built wheel (dist/)
      id: wheel-cache
      uses: actions/cache@v5
      with:
        path: dist/
        key: ${{ steps.artifact_key.outputs.artifact-key }}

    # Avoid serializing runs that already have a cached wheel.
    - name: Mutex on artifact key
      if: steps.wheel-cache.outputs.cache-hit != 'true'
      uses: softprops/turnstyle@v3
      with:
        poll-interval-seconds: 10
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TURNSTYLE_LOCK_KEY: ${{ steps.artifact_key.outputs.artifact-key }}

    # Re-check cache after acquiring the lock to avoid duplicate builds.
    - name: Re-check wheel cache under lock
      id: wheel-cache-recheck
      if: steps.wheel-cache.outputs.cache-hit != 'true'
      uses: actions/cache/restore@v5
      with:
        path: dist/
        key: ${{ steps.artifact_key.outputs.artifact-key }}

    - name: Determine wheel cache status
      id: wheel_cache_status
      shell: bash
      run: |
        if [[ "${{ steps.wheel-cache.outputs.cache-hit }}" == 'true' || "${{ steps.wheel-cache-recheck.outputs.cache-hit }}" == 'true' ]]; then
          echo "cache-hit=true" >> $GITHUB_OUTPUT
        else
          echo "cache-hit=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Python
      if: steps.wheel_cache_status.outputs.cache-hit != 'true'
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.pip-cache-dependency-path }}

    - name: Compute ccache restore-key prefix
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel_cache_status.outputs.cache-hit != 'true'
      id: ccache_restore_key
      shell: bash
      run: |
        RESTORE_KEY="BobTheBuidler/mypycify:ccache-data-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.build-from }}"
        echo "restore-key=$RESTORE_KEY" >> $GITHUB_OUTPUT

    - name: Compute ccache key
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel_cache_status.outputs.cache-hit != 'true'
      id: ccache_key
      shell: bash
      run: |
        CCACHE_KEY="${{ steps.ccache_restore_key.outputs.restore-key }}-${{ steps.hash_key.outputs.hash-key }}"
        echo "ccache-key=$CCACHE_KEY" >> $GITHUB_OUTPUT

    - name: Compute mypy cache restore-key prefix
      id: mypy_cache_restore_key
      if: steps.wheel_cache_status.outputs.cache-hit != 'true'
      shell: bash
      run: |
        MYPY_CACHE_PREFIX="BobTheBuidler/mypycify:mypy_cache-${{ runner.os }}-py${{ inputs.python-version }}-${{ inputs.build-from }}"
        echo "restore-key=$MYPY_CACHE_PREFIX" >> $GITHUB_OUTPUT

    - name: Restore mypy cache
      id: mypy_cache_restore
      if: steps.wheel_cache_status.outputs.cache-hit != 'true'
      uses: actions/cache/restore@v5
      with:
        path: .mypy_cache
        key: ${{ steps.mypy_cache_restore_key.outputs.restore-key }}-${{ steps.hash_key.outputs.hash-key }}
        restore-keys: ${{ steps.mypy_cache_restore_key.outputs.restore-key }}

    - name: Set ccache-dir variable
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel_cache_status.outputs.cache-hit != 'true'
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          echo "CCACHE_DIR=$HOME/.cache/ccache" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" = "macOS" ]; then
          echo "CCACHE_DIR=$HOME/Library/Caches/ccache" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install ccache on Linux
      if: inputs.ccache == 'true' && steps.wheel_cache_status.outputs.cache-hit != 'true' && runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y ccache
      shell: bash
    - name: Install ccache on macOS
      if: inputs.ccache == 'true' && steps.wheel_cache_status.outputs.cache-hit != 'true' && runner.os == 'macOS'
      run: brew install ccache
      shell: bash

    # Keep restore status for deciding whether saving is needed.
    - name: Restore ccache cache
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel_cache_status.outputs.cache-hit != 'true'
      id: ccache_restore
      uses: actions/cache/restore@v5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ steps.ccache_key.outputs.ccache-key }}
        restore-keys: ${{ steps.ccache_restore_key.outputs.restore-key }}

    - name: Show ccache config before build
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel_cache_status.outputs.cache-hit != 'true'
      run: |
        echo "ccache -- version && ccache -p"
        echo "==================== CCACHE CONFIG (BEFORE BUILD) ============================"
        ccache --version && ccache -p
        echo "============================================================================="
      shell: bash

    - name: Show ccache stats before build
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel_cache_status.outputs.cache-hit != 'true'
      run: |
        echo "ccache -s"
        echo "==================== CCACHE STATS (BEFORE BUILD) ============================="
        ccache -s
        echo "============================================================================="
      shell: bash

    - name: Install build dependencies
      if: steps.wheel_cache_status.outputs.cache-hit != 'true' && inputs.build-command == 'python -m build --wheel'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
      shell: bash

    - name: Build wheel from source (with ccache)
      if: inputs.ccache == 'true' && steps.wheel_cache_status.outputs.cache-hit != 'true' && inputs.build-from == 'source'
      env:
        CC: ccache gcc
      run: |
        echo "Running build command: ${{ inputs.build-command }}"
        eval "${{ inputs.build-command }}"
      shell: bash

    - name: Build wheel from source (without ccache)
      if: inputs.ccache != 'true' && steps.wheel_cache_status.outputs.cache-hit != 'true' && inputs.build-from == 'source'
      run: |
        echo "Running build command: ${{ inputs.build-command }}"
        eval "${{ inputs.build-command }}"
      shell: bash

    - name: Build wheel from sdist (with ccache)
      if: steps.wheel_cache_status.outputs.cache-hit != 'true' && inputs.build-from == 'sdist' && inputs.ccache == 'true'
      env:
        CC: ccache gcc
      run: |
        python -m pip install --upgrade build
        python -m build --sdist
        mkdir -p tmp_sdist_extract
        tar -xzf dist/*.tar.gz -C tmp_sdist_extract --strip-components=1
        cd tmp_sdist_extract
        echo "Running build command: ${{ inputs.build-command }}"
        eval "${{ inputs.build-command }}"
        cp dist/*.whl ../dist/
        cd ..
        rm -rf tmp_sdist_extract
      shell: bash

    - name: Build wheel from sdist (without ccache)
      if: steps.wheel_cache_status.outputs.cache-hit != 'true' && inputs.build-from == 'sdist' && inputs.ccache != 'true'
      run: |
        python -m pip install --upgrade build
        python -m build --sdist
        mkdir -p tmp_sdist_extract
        tar -xzf dist/*.tar.gz -C tmp_sdist_extract --strip-components=1
        cd tmp_sdist_extract
        echo "Running build command: ${{ inputs.build-command }}"
        eval "${{ inputs.build-command }}"
        cp dist/*.whl ../dist/
        cd ..
        rm -rf tmp_sdist_extract
      shell: bash

    - name: Show ccache stats after build
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel_cache_status.outputs.cache-hit != 'true'
      run: |
        echo "ccache -s"
        echo "==================== CCACHE STATS (AFTER BUILD) =============================="
        ccache -s
        echo "============================================================================="
      shell: bash

    - name: Save ccache cache
      # Skip saving when restore already hit to avoid redundant writes.
      if: inputs.ccache == 'true' && runner.os != 'Windows' && steps.wheel_cache_status.outputs.cache-hit != 'true' && steps.ccache_restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ steps.ccache_key.outputs.ccache-key }}

    # Avoid no-op writes when the wheel is cached or the mypy cache was restored.
    - name: Save mypy cache
      if: steps.wheel-cache.outputs.cache-hit != 'true' && steps.mypy_cache_restore.outputs.cache-hit != 'true'
      id: mypy_cache_save
      uses: actions/cache/save@v5
      with:
        path: .mypy_cache
        key: ${{ steps.mypy_cache_restore_key.outputs.restore-key }}-${{ steps.hash_key.outputs.hash-key }}

    - name: Compute unique artifact name
      id: artifact_name
      shell: bash
      run: |
        ARTIFACT_NAME="BobTheBuidler_mypycified_wheel-${{ steps.artifact_key.outputs.artifact-key }}"
        echo "artifact-name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT

    - name: Upload wheel artifact
      id: upload_artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ steps.artifact_name.outputs.artifact-name }}
        path: dist/*.whl
      continue-on-error: true

    - name: Delete dist/ after upload
      if: steps.upload_artifact.outcome == 'failure'
      shell: bash
      run: rm -rf dist/

    - name: Download wheel artifact
      if: steps.upload_artifact.outcome == 'failure'
      uses: actions/download-artifact@v7
      with:
        name: ${{ steps.artifact_name.outputs.artifact-name }}
        path: dist

    - name: Validate downloaded artifact
      if: steps.upload_artifact.outcome == 'failure'
      shell: bash
      run: |
        if [ "$(ls -1 dist/*.whl 2>/dev/null | wc -l)" -eq 1 ]; then
          echo "Artifact downloaded and validated."
          exit 0
        else
          echo "Artifact not found or multiple artifacts found."
          exit 1
        fi

    - name: Normalize C files for diffchecking
      if: inputs.normalize-source == 'true'
      run: |
        for f in build/*.c; do
          if ! grep -q 'DIFFCHECK_PLACEHOLDER' "$f"; then
            sed -i '1i#ifndef DIFFCHECK_PLACEHOLDER\n#define DIFFCHECK_PLACEHOLDER 0\n#endif' "$f"
          fi
        done
        sed -i 's/\(CPy_AddTraceback([^,]*, *[^,]*, *\)[0-9]\+\(, *[^)]*)\)/\1DIFFCHECK_PLACEHOLDER\2/g' build/*.c
        sed -i 's/CPyStatics\[[0-9]\+\]/CPyStatics[DIFFCHECK_PLACEHOLDER]/g' build/*.c
      shell: bash

    - name: Poosh Source
      if: inputs.push-source == 'true'
      uses: BobTheBuidler/poosh@v0.0.10
      with:
        trigger-pr-number: ${{ inputs.trigger-pr-number }}
        trigger-branch: ${{ inputs.trigger-branch-name }}
        pr-branch: mypycify/${{ inputs.trigger-branch-name }}
        pr-body: |
          This PR updates build artifacts based on the latest implementation. Generated by GitHub Actions.
          ${{ inputs.trigger-pr-number && format('Triggered by #{0}', inputs.trigger-pr-number) || (inputs.trigger-branch-name && format('Triggered by branch: {0}', inputs.trigger-branch-name) || '') }}
        commit-message: ${{ inputs.commit-message }}
